---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns01-account-key
    solvers:
      - selector:
          dnsZones:
            - internal.iosis.tech
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: letsencrypt-dns01-secret
              key: api-token